### ISSUE TITLE
您好能不能给一下input文件和attr文件的示例呢

### ISSUE THREAD

**Issue by lrcUnlimited** [zhihaoWangCHN/C4.5DecisionTreeBasedOnMapReduce#1]
您好能不能给一下input文件和attr文件的示例呢。

**Comment by WangZhihaoCHN** [comment]
您好
百度云
链接：http://pan.baidu.com/s/1jIiFpYm 密码：ugba

2017-02-10 16:27 GMT+08:00 lrcUnlimited <notifications@github.com>:

**Comment by lrcUnlimited** [comment]
好的，谢谢啦，能不能再给下那个算法的介绍呢，比如说你的博客啥的~有些地方没看太懂
